package com.schwab.orchestrator.core;

public enum AuditEventType {
    RUN_STARTED,
    STAGE_ENTERED,
    ENTRY_GATE_BLOCKED,
    STAGE_ATTEMPT_STARTED,
    STAGE_ATTEMPT_FAILED,
    STAGE_RETRY_SCHEDULED,
    STAGE_FALLBACK_INVOKED,
    EXIT_GATE_BLOCKED,
    GUARDRAIL_BLOCKED,
    STAGE_SUCCEEDED,
    STAGE_FAILED,
    STAGE_SKIPPED,
    STAGE_WAITING_APPROVAL,
    STAGE_APPROVED,
    STAGE_REJECTED,
    STAGE_ROLLED_BACK,
    STAGE_INVALIDATED,
    CONTEXT_ARTIFACT_UPDATED,
    SAFE_STOP_TRIGGERED,
    RUN_COMPLETED
}
